export const ADD_TODO = "ADD_TODO"
export const SET_DONE = "SET_DONE"
export const REMOVE_TODO = "REMOVE_TODO"
export const SET_UPDATE = "SET_UPDATE"
export const SET_LIMIT = "SET_LIMIT"
export const SET_TODO = "SET_TODO"
export const RESET_LIMIT = "RESET_LIMIT"
